twig:
  default_path: "%kernel.project_dir%/templates"
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  exception_controller: null
  form_themes: ["bootstrap_4_horizontal_layout.html.twig"] # Refer to https://symfony.com/doc/4.4/form/form_themes.html
